media:
  input: public
  output: /

content:
  - name: meetups
    label: Meetups
    type: collection
    path: src/content/meetups
    format: json
    filename: '{fields.filename_convention}.json'
    view:
      primary: title
      fields: [title, date, location.venue]
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: date
        options:
          format: 'yyyy-MM-dd'
          time: false
        required: true

      - name: startTime
        label: Start Time (HH:MM)
        type: string
        required: true

      - name: endTime
        label: End Time (HH:MM)
        type: string
        required: true

      - name: location
        label: Location
        type: object
        required: true
        fields:
          - name: venue
            label: Venue Name
            type: string
            required: true
          - name: address
            label: Full Address
            type: text
            required: true
          - name: mapLink
            label: Google Maps Link (Optional)
            type: string
            required: false

      - name: meetupUrl
        label: Meetup.com URL (or similar)
        type: string
        required: true

      - name: description
        label: Event Description
        type: object
        required: true
        fields:
          - name: markdown
            label: Content
            type: rich-text
            required: true

      - name: filename_convention
        label: Filename Convention (e.g., meetup-may-25)
        type: string
        required: true
        description: "Enter the JSON filename base. Convention: `meetup-[month]-[yy]`, using the full lowercase month and a two-digit year (e.g., `meetup-may-25`)."

      - name: slug
        label: URL Slug (Optional)
        type: string
        required: false
        description: "Leave blank to let Astro auto-generate the URL (e.g., '2025-05-29-title'). If you fill this, it will override Astro's auto-generated URL slug."

      - name: talks
        label: Talks
        type: object
        list: true
        required: true
        fields:
          - name: speaker
            label: Speaker Details
            type: object
            required: true
            fields:
              - name: name
                label: Speaker Name
                type: string
                required: true
              - name: role
                label: Speaker Role (Optional)
                type: string
                required: false
          - name: title
            label: Talk Title
            type: string
            required: true

      - name: sponsors
        label: Sponsors (Optional)
        type: object
        list: true
        required: false
        fields:
          - name: name
            label: Sponsor Name
            type: string
            required: true
          - name: logo
            label: Sponsor Logo
            type: image
            options:
              path: sponsors
            required: true
          - name: url
            label: Sponsor Website URL
            type: string
            required: true

      - name: organizers
        label: Organizers
        type: object
        list: true
        required: true
        default:
          - name: James McLeod
            role: Open Source Program Lead, NatWest Group
            linkedin: https://www.linkedin.com/in/jamesmcleod/
            website: null
          - name: Jordan Potts
            role: Head of Contract, Albany Growth
            linkedin: https://www.linkedin.com/in/jordan-potts-numi/
            website: null
          - name: Will Laing
            role: Co-Founder, Plan:it
            linkedin: https://www.linkedin.com/in/willhlaing/
            website: https://weareplanit.com/
        fields:
          - name: name
            label: Organizer Name
            type: string
            required: true
          - name: role
            label: Organizer Role
            type: string
            required: true
          - name: linkedin
            label: LinkedIn Profile URL
            type: string
            required: true
          - name: website
            label: Personal Website URL (Optional)
            type: string
            required: false

      - name: refreshments
        label: Refreshments Information
        type: object
        required: true
        default:
          description: "A variety of food & drink will be served. We will endeavour to cater for allergies & dietary requirements. This won't just be pizza & beer either..."
          markdown: true
        fields:
          - name: description
            label: Description of Refreshments
            type: text
            required: true
          - name: markdown
            label: Is description in Markdown format?
            type: boolean
            required: true

      - name: thingsToNote
        label: Important Notes
        type: object
        required: true
        default:
          items:
            - "A desire to explore JavaScript from different points of view is absolutely recommended"
            - "Feel free to bring your JS projects along"
            - "All engineering levels are welcome"
            - "Please RSVP to secure a place"
            - "Please ask plus 1's to sign up to the group & RSVP"
            - "Spaces are limited so techies get priority"
          markdown: false
        fields:
          - name: items
            label: List of Notes
            type: string
            list: true
            required: true
          - name: markdown
            label: Are notes in Markdown format?
            type: boolean
            required: true

      - name: codeOfConductUrl
        label: Code of Conduct URL
        type: string
        required: true
        default: "http://confcodeofconduct.com"
