blank_issues_enabled: false
contact_links:
  - name: London.js Meetup Group
    url: https://www.meetup.com/london-js/
    description: For questions about events, membership, or general inquiries, please visit our Meetup group.
